package cn.csnbgsh.herbarium.entity

import java.io.Serializable

class Collection : Serializable {
    var ID = ""
    var MuseumID = ""
    var CollBarcode = ""
    var Collector = ""
    var CollectSN = ""
    var CollectTeam = ""
    var ResearchGroup = ""
    var CollYear = ""
    var CollectDay = ""
    var CollDay_origin = ""
    var Country = ""
    var Province = ""
    var City = ""
    var Place = ""
    var Longitude = ""
    var Latitude = ""
    var Altitude = ""
    var Lon_origin = ""
    var Alt_origin = ""
    var Environment = ""
    var Habit = ""
    var Height = ""
    var Leaf = ""
    var Flower = ""
    var Fruit = ""
    var LocalName = ""
    var Family = ""
    var Genus = ""
    var Name = ""
    var SpecimenCount = ""
    var LiveSampleCount = ""
    var CollectMemo = ""
    var Editor = ""
    var EditorMemo = ""
    var CreateTime = ""
    var UpdateTime = ""
}