package cn.csnbgsh.herbarium.entity

import java.io.Serializable

class Specimen : Serializable {
    var ID = ""
    var MuseumID = ""
    var CollectID = ""
    var Barcode = ""
    var SN = ""
    var IsType = ""
    var Type = ""
    var HasFlower = ""
    var HasFruit = ""
    var Photos = ""
    var PhotoCount = ""
    var Store = ""
    var TaxonLevel = ""
    var SPID = ""
    var CanonicalName = ""
    var CommonName = ""
    var SpName = ""
    var SubSpname = ""
    var Family = ""
    var FamilyCName = ""
    var Genus = ""
    var GenusCName = ""
    var IdentMan = ""
    var SavePlace = ""
    var Building = ""
    var Room = ""
    var Cabinet = ""
    var Box = ""
    var Memo = ""
    var ShareMode = ""
    var Editor = ""
    var Status = ""
    var CreateTime = ""
    var UpdateTime = ""
}